Feature/updatebuilds
viur-framework/viur-cli pull request #103
Opened 2024-01-26 15:50 UTC by Grashalmbeisser

2024-01-31 22:48 UTC, sveneberth requested changes

2024-01-31 22:48 UTC, sveneberth commented on src/viur_cli/install.py
> +        checkreturncode(output)
```suggestion
@install.command()
@click.argument("action", type=click.Choice(["vi", "admin", "scriptor", "all"]))
@click.argument("profile", default='default')
def update(action, profile):
    """Updates all ViUR Ecosystem Components"""
    conf = config.get_profile(profile)
   
    def run_single_action(action: str) -> None:
        echo_info(f"Updating {build} …")
        output = subprocess.run(f"viur install {action} latest {profile}",
                                capture_output=True, check=True, shell=True)
        if output.returncode == 0:
            echo_positive("update was successful")
        else:
            echo_fatal("update exited with a non zero success code")
    
    if action == "all":
        # Get the builds of the project.json profile
        for build in conf["builds"]:
            run_single_action(build)
    # This function is obsolete, however the user might expect this behavior.
    else:
        run_single_action(action)
```

2024-01-31 22:53 UTC, sveneberth commented
The command name is IMO not the best. `viur install update` means you install the component `update`, not you perform an update.

2024-02-01 17:11 UTC, Grashalmbeisser commented
> The command name is IMO not the best. `viur install update` means you install the component `update`, not you perform an update.

You have a point, i refactored everything again and the command group is now "package"

2024-02-09 14:26 UTC, phorward requested changes
Okay for the first version. I think there's still stuff which can be optimized.

2024-02-09 14:26 UTC, phorward commented on README.md
> +- `version`  version you want to install
```suggestion
handles ViUR ecosystem package operations

Commands:
- `install`  installs a ViUR package (in a specific version)
- `update`   updates a ViUR package to the newest version

Arguments:
- `profile`  profile to install to
- `version`  version to install
```

2024-02-19 12:54 UTC, merged