added support for cloudfunction gen2
viur-framework/viur-cli pull request #181
Opened 2024-10-11 17:12 UTC by Grashalmbeisser

2024-10-11 19:29 UTC, sveneberth requested changes

2024-10-11 19:29 UTC, sveneberth commented on src/viur_cli/cloud.py
> +                                                        "Enter the directory of your cloud functio"
```suggestion
                                                        "Enter the directory of your cloud function"
```

2024-10-11 19:29 UTC, sveneberth commented on src/viur_cli/cloud.py
It looks like Google has renamed this: https://cloud.google.com/blog/products/serverless/google-cloud-functions-is-now-cloud-run-functions?hl=en

Can you check and if so, rename it to _"Cloud Run functions"_ with the correct spelling so it doesn't confuse.

2024-10-29 13:37 UTC, Grashalmbeisser commented on src/viur_cli/cloud.py
I would like to wait with the Namechange untill google Established the Spelling "Cloud Run functions" throughout their documentation. Since the deployment of cloud functions works with the `cloud run` command but i  could not find this command in the documentation yet.

2024-11-08 11:08 UTC, akelch approved these changes

2024-11-08 11:21 UTC, merged