Feature/gcloud functions
viur-framework/viur-cli pull request #98
Opened 2024-01-19 15:36 UTC by Grashalmbeisser

- Merged with main
- Implemented gcloud setup in viur cli
- Role administration via cli is now possible
- cloud function creation, deployment  via cli
- enable and disable backups via cli
-

2024-01-31 22:38 UTC, sveneberth requested changes

2024-01-31 22:38 UTC, sveneberth commented on src/viur_cli/cloud.py
>          echo_fatal("Usage: python scrtipt.py PROJECT_ID")
btw: What's _scrtipt.py_?

Shouldn't this be sth like
```suggestion
        echo_fatal("Usage: viur setup gcloud PROJECT_ID")
```
?

2024-01-31 22:38 UTC, sveneberth commented on src/viur_cli/cloud.py
> +        return output
Looks like a forgotten debug print. Or not?

```suggestion
        return subprocess.check_output(command, shell=True)
```

2024-02-09 14:31 UTC, phorward requested changes
Hello @Grashalmbeisser,

thanks for the many new functions.
1. Next time you rename a file, use `git mv deploy.py cloud.py` instead of copying the content from `deploy.py` into `cloud.py` and remove `deploy.py`.
2. Avoid using `print`, use the cli output functions
3. You should use the `click` facilities to implement optional prompts, and not use 'input` for this.

2024-02-09 14:31 UTC, phorward commented on src/viur_cli/cloud.py
> +        print(result)
```suggestion
```

2024-02-09 14:31 UTC, phorward commented on src/viur_cli/cloud.py
> +            print('Error creating bucket.')
Use the cli-output utilities.
```suggestion
            echo_error('Error creating bucket.')
```

2024-02-09 14:31 UTC, phorward commented on src/viur_cli/cloud.py
> +        response = input("Are you ready?[Y/n]")
Use the `click` package and its features here. This will also make gcloud_setup() parametrizable directly, so no prompts occur.

2024-02-19 12:59 UTC, merged